language: python
git:
    depth: 1
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
script:
    - python -c "import sqlmap; import sqlmapapi"
    - python sqlmap.py --smoke
    - python sqlmap.py --vuln
